FROM golang:1.8-alpine

RUN apk add --no-cache python2
RUN apk add --no-cache ffmpeg
RUN apk add --no-cache sqlite
RUN apk add --no-cache wget

RUN wget -q https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl --no-check-certificate
RUN chmod a+rx /usr/local/bin/youtube-dl

RUN mkdir -p /recordings

WORKDIR /app
RUN mkdir -p docs

COPY go.mod .

# Get dependancies - will also be cached if we won't change mod/sum
RUN go mod download

COPY . .

COPY conf/app.docker.yml conf/app.yml
RUN mkdir -p /usr/share/fonts/truetype/
COPY ./assets/DMMono-Regular.ttf /usr/share/fonts/truetype/

# https://github.com/mattn/go-sqlite3/issues/803
RUN go install github.com/swaggo/swag/cmd/swag
RUN swag init
RUN GOFLAGS="-g -O2 -Wno-return-local-addr"
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./streamsink

EXPOSE 3000

CMD [ "./streamsink" ]