version: "3.9"

services:
  recordings:
    image: nginx
    volumes:
     - /slurm/streamsink/recordings:/usr/share/nginx/html:ro
    ports:
     - "4000:80"

  streamsink-vue:
    image: sedrad/streamsink-vue
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '80:80'
    environment:
      - APP_API_URL=http://192.168.0.219:3000/api/v1
      - APP_BASE=http://192.168.0.219:3000
      - APP_NAME=Streamsink
      - APP_FILEURL=http://192.168.0.219:4000
      - APP_SOCKETURL=http://192.168.0.219:3000/api/v1/ws

  streamsink-go:
    image: sedrad/streamsink-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '3000:3000'
    volumes:
      - /slurm/streamsink/recordings:/recordings
      - /slurm:/disk
