// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/srad/mediasink/ent/command"
)

// CommandCreate is the builder for creating a Command entity.
type CommandCreate struct {
	config
	mutation *CommandMutation
	hooks    []Hook
}

// SetPid sets the "pid" field.
func (cc *CommandCreate) SetPid(i int) *CommandCreate {
	cc.mutation.SetPid(i)
	return cc
}

// SetNillablePid sets the "pid" field if the given value is not nil.
func (cc *CommandCreate) SetNillablePid(i *int) *CommandCreate {
	if i != nil {
		cc.SetPid(*i)
	}
	return cc
}

// SetCommand sets the "command" field.
func (cc *CommandCreate) SetCommand(s string) *CommandCreate {
	cc.mutation.SetCommand(s)
	return cc
}

// SetProgress sets the "progress" field.
func (cc *CommandCreate) SetProgress(s string) *CommandCreate {
	cc.mutation.SetProgress(s)
	return cc
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (cc *CommandCreate) SetNillableProgress(s *string) *CommandCreate {
	if s != nil {
		cc.SetProgress(*s)
	}
	return cc
}

// SetInfo sets the "info" field.
func (cc *CommandCreate) SetInfo(s string) *CommandCreate {
	cc.mutation.SetInfo(s)
	return cc
}

// SetNillableInfo sets the "info" field if the given value is not nil.
func (cc *CommandCreate) SetNillableInfo(s *string) *CommandCreate {
	if s != nil {
		cc.SetInfo(*s)
	}
	return cc
}

// SetArgs sets the "args" field.
func (cc *CommandCreate) SetArgs(s string) *CommandCreate {
	cc.mutation.SetArgs(s)
	return cc
}

// SetNillableArgs sets the "args" field if the given value is not nil.
func (cc *CommandCreate) SetNillableArgs(s *string) *CommandCreate {
	if s != nil {
		cc.SetArgs(*s)
	}
	return cc
}

// Mutation returns the CommandMutation object of the builder.
func (cc *CommandCreate) Mutation() *CommandMutation {
	return cc.mutation
}

// Save creates the Command in the database.
func (cc *CommandCreate) Save(ctx context.Context) (*Command, error) {
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CommandCreate) SaveX(ctx context.Context) *Command {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CommandCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CommandCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CommandCreate) check() error {
	if _, ok := cc.mutation.Command(); !ok {
		return &ValidationError{Name: "command", err: errors.New(`ent: missing required field "Command.command"`)}
	}
	return nil
}

func (cc *CommandCreate) sqlSave(ctx context.Context) (*Command, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *CommandCreate) createSpec() (*Command, *sqlgraph.CreateSpec) {
	var (
		_node = &Command{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(command.Table, sqlgraph.NewFieldSpec(command.FieldID, field.TypeInt))
	)
	if value, ok := cc.mutation.Pid(); ok {
		_spec.SetField(command.FieldPid, field.TypeInt, value)
		_node.Pid = value
	}
	if value, ok := cc.mutation.Command(); ok {
		_spec.SetField(command.FieldCommand, field.TypeString, value)
		_node.Command = value
	}
	if value, ok := cc.mutation.Progress(); ok {
		_spec.SetField(command.FieldProgress, field.TypeString, value)
		_node.Progress = value
	}
	if value, ok := cc.mutation.Info(); ok {
		_spec.SetField(command.FieldInfo, field.TypeString, value)
		_node.Info = value
	}
	if value, ok := cc.mutation.Args(); ok {
		_spec.SetField(command.FieldArgs, field.TypeString, value)
		_node.Args = value
	}
	return _node, _spec
}

// CommandCreateBulk is the builder for creating many Command entities in bulk.
type CommandCreateBulk struct {
	config
	err      error
	builders []*CommandCreate
}

// Save creates the Command entities in the database.
func (ccb *CommandCreateBulk) Save(ctx context.Context) ([]*Command, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Command, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CommandMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CommandCreateBulk) SaveX(ctx context.Context) []*Command {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CommandCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CommandCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
