// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/srad/mediasink/ent/job"
	"github.com/srad/mediasink/ent/predicate"
)

// JobUpdate is the builder for updating Job entities.
type JobUpdate struct {
	config
	hooks    []Hook
	mutation *JobMutation
}

// Where appends a list predicates to the JobUpdate builder.
func (ju *JobUpdate) Where(ps ...predicate.Job) *JobUpdate {
	ju.mutation.Where(ps...)
	return ju
}

// SetType sets the "type" field.
func (ju *JobUpdate) SetType(s string) *JobUpdate {
	ju.mutation.SetType(s)
	return ju
}

// SetNillableType sets the "type" field if the given value is not nil.
func (ju *JobUpdate) SetNillableType(s *string) *JobUpdate {
	if s != nil {
		ju.SetType(*s)
	}
	return ju
}

// SetPayload sets the "payload" field.
func (ju *JobUpdate) SetPayload(b []byte) *JobUpdate {
	ju.mutation.SetPayload(b)
	return ju
}

// SetStatus sets the "status" field.
func (ju *JobUpdate) SetStatus(j job.Status) *JobUpdate {
	ju.mutation.SetStatus(j)
	return ju
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ju *JobUpdate) SetNillableStatus(j *job.Status) *JobUpdate {
	if j != nil {
		ju.SetStatus(*j)
	}
	return ju
}

// SetAttemptCount sets the "attempt_count" field.
func (ju *JobUpdate) SetAttemptCount(i int) *JobUpdate {
	ju.mutation.ResetAttemptCount()
	ju.mutation.SetAttemptCount(i)
	return ju
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (ju *JobUpdate) SetNillableAttemptCount(i *int) *JobUpdate {
	if i != nil {
		ju.SetAttemptCount(*i)
	}
	return ju
}

// AddAttemptCount adds i to the "attempt_count" field.
func (ju *JobUpdate) AddAttemptCount(i int) *JobUpdate {
	ju.mutation.AddAttemptCount(i)
	return ju
}

// SetLastError sets the "last_error" field.
func (ju *JobUpdate) SetLastError(s string) *JobUpdate {
	ju.mutation.SetLastError(s)
	return ju
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (ju *JobUpdate) SetNillableLastError(s *string) *JobUpdate {
	if s != nil {
		ju.SetLastError(*s)
	}
	return ju
}

// ClearLastError clears the value of the "last_error" field.
func (ju *JobUpdate) ClearLastError() *JobUpdate {
	ju.mutation.ClearLastError()
	return ju
}

// SetDetails sets the "details" field.
func (ju *JobUpdate) SetDetails(s string) *JobUpdate {
	ju.mutation.SetDetails(s)
	return ju
}

// SetNillableDetails sets the "details" field if the given value is not nil.
func (ju *JobUpdate) SetNillableDetails(s *string) *JobUpdate {
	if s != nil {
		ju.SetDetails(*s)
	}
	return ju
}

// ClearDetails clears the value of the "details" field.
func (ju *JobUpdate) ClearDetails() *JobUpdate {
	ju.mutation.ClearDetails()
	return ju
}

// SetUpdatedAt sets the "updated_at" field.
func (ju *JobUpdate) SetUpdatedAt(t time.Time) *JobUpdate {
	ju.mutation.SetUpdatedAt(t)
	return ju
}

// Mutation returns the JobMutation object of the builder.
func (ju *JobUpdate) Mutation() *JobMutation {
	return ju.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ju *JobUpdate) Save(ctx context.Context) (int, error) {
	ju.defaults()
	return withHooks(ctx, ju.sqlSave, ju.mutation, ju.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ju *JobUpdate) SaveX(ctx context.Context) int {
	affected, err := ju.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ju *JobUpdate) Exec(ctx context.Context) error {
	_, err := ju.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ju *JobUpdate) ExecX(ctx context.Context) {
	if err := ju.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ju *JobUpdate) defaults() {
	if _, ok := ju.mutation.UpdatedAt(); !ok {
		v := job.UpdateDefaultUpdatedAt()
		ju.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ju *JobUpdate) check() error {
	if v, ok := ju.mutation.GetType(); ok {
		if err := job.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Job.type": %w`, err)}
		}
	}
	if v, ok := ju.mutation.Payload(); ok {
		if err := job.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "Job.payload": %w`, err)}
		}
	}
	if v, ok := ju.mutation.Status(); ok {
		if err := job.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Job.status": %w`, err)}
		}
	}
	if v, ok := ju.mutation.AttemptCount(); ok {
		if err := job.AttemptCountValidator(v); err != nil {
			return &ValidationError{Name: "attempt_count", err: fmt.Errorf(`ent: validator failed for field "Job.attempt_count": %w`, err)}
		}
	}
	return nil
}

func (ju *JobUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ju.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID))
	if ps := ju.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ju.mutation.GetType(); ok {
		_spec.SetField(job.FieldType, field.TypeString, value)
	}
	if value, ok := ju.mutation.Payload(); ok {
		_spec.SetField(job.FieldPayload, field.TypeBytes, value)
	}
	if value, ok := ju.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := ju.mutation.AttemptCount(); ok {
		_spec.SetField(job.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := ju.mutation.AddedAttemptCount(); ok {
		_spec.AddField(job.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := ju.mutation.LastError(); ok {
		_spec.SetField(job.FieldLastError, field.TypeString, value)
	}
	if ju.mutation.LastErrorCleared() {
		_spec.ClearField(job.FieldLastError, field.TypeString)
	}
	if value, ok := ju.mutation.Details(); ok {
		_spec.SetField(job.FieldDetails, field.TypeString, value)
	}
	if ju.mutation.DetailsCleared() {
		_spec.ClearField(job.FieldDetails, field.TypeString)
	}
	if value, ok := ju.mutation.UpdatedAt(); ok {
		_spec.SetField(job.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ju.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ju.mutation.done = true
	return n, nil
}

// JobUpdateOne is the builder for updating a single Job entity.
type JobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobMutation
}

// SetType sets the "type" field.
func (juo *JobUpdateOne) SetType(s string) *JobUpdateOne {
	juo.mutation.SetType(s)
	return juo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableType(s *string) *JobUpdateOne {
	if s != nil {
		juo.SetType(*s)
	}
	return juo
}

// SetPayload sets the "payload" field.
func (juo *JobUpdateOne) SetPayload(b []byte) *JobUpdateOne {
	juo.mutation.SetPayload(b)
	return juo
}

// SetStatus sets the "status" field.
func (juo *JobUpdateOne) SetStatus(j job.Status) *JobUpdateOne {
	juo.mutation.SetStatus(j)
	return juo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableStatus(j *job.Status) *JobUpdateOne {
	if j != nil {
		juo.SetStatus(*j)
	}
	return juo
}

// SetAttemptCount sets the "attempt_count" field.
func (juo *JobUpdateOne) SetAttemptCount(i int) *JobUpdateOne {
	juo.mutation.ResetAttemptCount()
	juo.mutation.SetAttemptCount(i)
	return juo
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableAttemptCount(i *int) *JobUpdateOne {
	if i != nil {
		juo.SetAttemptCount(*i)
	}
	return juo
}

// AddAttemptCount adds i to the "attempt_count" field.
func (juo *JobUpdateOne) AddAttemptCount(i int) *JobUpdateOne {
	juo.mutation.AddAttemptCount(i)
	return juo
}

// SetLastError sets the "last_error" field.
func (juo *JobUpdateOne) SetLastError(s string) *JobUpdateOne {
	juo.mutation.SetLastError(s)
	return juo
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableLastError(s *string) *JobUpdateOne {
	if s != nil {
		juo.SetLastError(*s)
	}
	return juo
}

// ClearLastError clears the value of the "last_error" field.
func (juo *JobUpdateOne) ClearLastError() *JobUpdateOne {
	juo.mutation.ClearLastError()
	return juo
}

// SetDetails sets the "details" field.
func (juo *JobUpdateOne) SetDetails(s string) *JobUpdateOne {
	juo.mutation.SetDetails(s)
	return juo
}

// SetNillableDetails sets the "details" field if the given value is not nil.
func (juo *JobUpdateOne) SetNillableDetails(s *string) *JobUpdateOne {
	if s != nil {
		juo.SetDetails(*s)
	}
	return juo
}

// ClearDetails clears the value of the "details" field.
func (juo *JobUpdateOne) ClearDetails() *JobUpdateOne {
	juo.mutation.ClearDetails()
	return juo
}

// SetUpdatedAt sets the "updated_at" field.
func (juo *JobUpdateOne) SetUpdatedAt(t time.Time) *JobUpdateOne {
	juo.mutation.SetUpdatedAt(t)
	return juo
}

// Mutation returns the JobMutation object of the builder.
func (juo *JobUpdateOne) Mutation() *JobMutation {
	return juo.mutation
}

// Where appends a list predicates to the JobUpdate builder.
func (juo *JobUpdateOne) Where(ps ...predicate.Job) *JobUpdateOne {
	juo.mutation.Where(ps...)
	return juo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (juo *JobUpdateOne) Select(field string, fields ...string) *JobUpdateOne {
	juo.fields = append([]string{field}, fields...)
	return juo
}

// Save executes the query and returns the updated Job entity.
func (juo *JobUpdateOne) Save(ctx context.Context) (*Job, error) {
	juo.defaults()
	return withHooks(ctx, juo.sqlSave, juo.mutation, juo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (juo *JobUpdateOne) SaveX(ctx context.Context) *Job {
	node, err := juo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (juo *JobUpdateOne) Exec(ctx context.Context) error {
	_, err := juo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (juo *JobUpdateOne) ExecX(ctx context.Context) {
	if err := juo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (juo *JobUpdateOne) defaults() {
	if _, ok := juo.mutation.UpdatedAt(); !ok {
		v := job.UpdateDefaultUpdatedAt()
		juo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (juo *JobUpdateOne) check() error {
	if v, ok := juo.mutation.GetType(); ok {
		if err := job.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Job.type": %w`, err)}
		}
	}
	if v, ok := juo.mutation.Payload(); ok {
		if err := job.PayloadValidator(v); err != nil {
			return &ValidationError{Name: "payload", err: fmt.Errorf(`ent: validator failed for field "Job.payload": %w`, err)}
		}
	}
	if v, ok := juo.mutation.Status(); ok {
		if err := job.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Job.status": %w`, err)}
		}
	}
	if v, ok := juo.mutation.AttemptCount(); ok {
		if err := job.AttemptCountValidator(v); err != nil {
			return &ValidationError{Name: "attempt_count", err: fmt.Errorf(`ent: validator failed for field "Job.attempt_count": %w`, err)}
		}
	}
	return nil
}

func (juo *JobUpdateOne) sqlSave(ctx context.Context) (_node *Job, err error) {
	if err := juo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeUUID))
	id, ok := juo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Job.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := juo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, job.FieldID)
		for _, f := range fields {
			if !job.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != job.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := juo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := juo.mutation.GetType(); ok {
		_spec.SetField(job.FieldType, field.TypeString, value)
	}
	if value, ok := juo.mutation.Payload(); ok {
		_spec.SetField(job.FieldPayload, field.TypeBytes, value)
	}
	if value, ok := juo.mutation.Status(); ok {
		_spec.SetField(job.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := juo.mutation.AttemptCount(); ok {
		_spec.SetField(job.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := juo.mutation.AddedAttemptCount(); ok {
		_spec.AddField(job.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := juo.mutation.LastError(); ok {
		_spec.SetField(job.FieldLastError, field.TypeString, value)
	}
	if juo.mutation.LastErrorCleared() {
		_spec.ClearField(job.FieldLastError, field.TypeString)
	}
	if value, ok := juo.mutation.Details(); ok {
		_spec.SetField(job.FieldDetails, field.TypeString, value)
	}
	if juo.mutation.DetailsCleared() {
		_spec.ClearField(job.FieldDetails, field.TypeString)
	}
	if value, ok := juo.mutation.UpdatedAt(); ok {
		_spec.SetField(job.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Job{config: juo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, juo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	juo.mutation.done = true
	return _node, nil
}
