// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/srad/mediasink/ent/recording"
)

// Recording is the model entity for the Recording schema.
type Recording struct {
	config
	// ID of the ent.
	ID                 int `json:"id,omitempty"`
	channel_recordings *int
	selectValues       sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Recording) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case recording.FieldID:
			values[i] = new(sql.NullInt64)
		case recording.ForeignKeys[0]: // channel_recordings
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Recording fields.
func (r *Recording) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case recording.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			r.ID = int(value.Int64)
		case recording.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field channel_recordings", value)
			} else if value.Valid {
				r.channel_recordings = new(int)
				*r.channel_recordings = int(value.Int64)
			}
		default:
			r.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Recording.
// This includes values selected through modifiers, order, etc.
func (r *Recording) Value(name string) (ent.Value, error) {
	return r.selectValues.Get(name)
}

// Update returns a builder for updating this Recording.
// Note that you need to call Recording.Unwrap() before calling this method if this Recording
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Recording) Update() *RecordingUpdateOne {
	return NewRecordingClient(r.config).UpdateOne(r)
}

// Unwrap unwraps the Recording entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Recording) Unwrap() *Recording {
	_tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Recording is not a transactional entity")
	}
	r.config.driver = _tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Recording) String() string {
	var builder strings.Builder
	builder.WriteString("Recording(")
	builder.WriteString(fmt.Sprintf("id=%v", r.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Recordings is a parsable slice of Recording.
type Recordings []*Recording
