// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/srad/mediasink/ent/channel"
	"github.com/srad/mediasink/ent/job"
	"github.com/srad/mediasink/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	channelFields := schema.Channel{}.Fields()
	_ = channelFields
	// channelDescChannelName is the schema descriptor for channel_name field.
	channelDescChannelName := channelFields[0].Descriptor()
	// channel.ChannelNameValidator is a validator for the "channel_name" field. It is called by the builders before save.
	channel.ChannelNameValidator = channelDescChannelName.Validators[0].(func(string) error)
	// channelDescDisplayName is the schema descriptor for display_name field.
	channelDescDisplayName := channelFields[1].Descriptor()
	// channel.DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	channel.DisplayNameValidator = channelDescDisplayName.Validators[0].(func(string) error)
	// channelDescSkipStart is the schema descriptor for skip_start field.
	channelDescSkipStart := channelFields[2].Descriptor()
	// channel.DefaultSkipStart holds the default value on creation for the skip_start field.
	channel.DefaultSkipStart = channelDescSkipStart.Default.(uint)
	// channelDescURL is the schema descriptor for url field.
	channelDescURL := channelFields[4].Descriptor()
	// channel.URLValidator is a validator for the "url" field. It is called by the builders before save.
	channel.URLValidator = channelDescURL.Validators[0].(func(string) error)
	// channelDescIsFav is the schema descriptor for is_fav field.
	channelDescIsFav := channelFields[5].Descriptor()
	// channel.DefaultIsFav holds the default value on creation for the is_fav field.
	channel.DefaultIsFav = channelDescIsFav.Default.(bool)
	// channelDescIsPaused is the schema descriptor for is_paused field.
	channelDescIsPaused := channelFields[6].Descriptor()
	// channel.DefaultIsPaused holds the default value on creation for the is_paused field.
	channel.DefaultIsPaused = channelDescIsPaused.Default.(bool)
	// channelDescIsDeleted is the schema descriptor for is_deleted field.
	channelDescIsDeleted := channelFields[7].Descriptor()
	// channel.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	channel.DefaultIsDeleted = channelDescIsDeleted.Default.(bool)
	// channelDescCreatedAt is the schema descriptor for created_at field.
	channelDescCreatedAt := channelFields[8].Descriptor()
	// channel.DefaultCreatedAt holds the default value on creation for the created_at field.
	channel.DefaultCreatedAt = channelDescCreatedAt.Default.(func() time.Time)
	jobFields := schema.Job{}.Fields()
	_ = jobFields
	// jobDescType is the schema descriptor for type field.
	jobDescType := jobFields[1].Descriptor()
	// job.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	job.TypeValidator = jobDescType.Validators[0].(func(string) error)
	// jobDescPayload is the schema descriptor for payload field.
	jobDescPayload := jobFields[2].Descriptor()
	// job.PayloadValidator is a validator for the "payload" field. It is called by the builders before save.
	job.PayloadValidator = jobDescPayload.Validators[0].(func([]byte) error)
	// jobDescAttemptCount is the schema descriptor for attempt_count field.
	jobDescAttemptCount := jobFields[4].Descriptor()
	// job.DefaultAttemptCount holds the default value on creation for the attempt_count field.
	job.DefaultAttemptCount = jobDescAttemptCount.Default.(int)
	// job.AttemptCountValidator is a validator for the "attempt_count" field. It is called by the builders before save.
	job.AttemptCountValidator = jobDescAttemptCount.Validators[0].(func(int) error)
	// jobDescCreatedAt is the schema descriptor for created_at field.
	jobDescCreatedAt := jobFields[6].Descriptor()
	// job.DefaultCreatedAt holds the default value on creation for the created_at field.
	job.DefaultCreatedAt = jobDescCreatedAt.Default.(func() time.Time)
	// jobDescUpdatedAt is the schema descriptor for updated_at field.
	jobDescUpdatedAt := jobFields[7].Descriptor()
	// job.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	job.DefaultUpdatedAt = jobDescUpdatedAt.Default.(func() time.Time)
	// job.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	job.UpdateDefaultUpdatedAt = jobDescUpdatedAt.UpdateDefault.(func() time.Time)
	// jobDescID is the schema descriptor for id field.
	jobDescID := jobFields[0].Descriptor()
	// job.DefaultID holds the default value on creation for the id field.
	job.DefaultID = jobDescID.Default.(func() uuid.UUID)
}
