// Code generated by ent, DO NOT EDIT.

package recording

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the recording type in the database.
	Label = "recording"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the recording in the database.
	Table = "recordings"
)

// Columns holds all SQL columns for recording fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "recordings"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"channel_recordings",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Recording queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}
