// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Channel is the predicate function for channel builders.
type Channel func(*sql.Selector)

// Command is the predicate function for command builders.
type Command func(*sql.Selector)

// Job is the predicate function for job builders.
type Job func(*sql.Selector)

// Recording is the predicate function for recording builders.
type Recording func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
